apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: blue-green
    project: roboshop
    target: preview
spec:
  selector:
    purpose: blue-green
    project: roboshop
    color: green
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port